language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - autoconf
    - automake
    - libtool
    - libbz2-dev
    - liblzma-dev
    - libcurl4-openssl-dev
    - libcrypto++-dev
    - zlib1g-dev
  homebrew:
    packages:
    - autoconf
    - automake
    - libtool
    - xz
    - curl
    - openssl


sudo: required
install:
  - cd ../
  - ls
  - wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2
  - tar -xvjf htslib-1.9.tar.bz2
  - sudo mv htslib-1.9/ htslib/
  - pushd htslib && ./configure --prefix=/usr && make && sudo make install && popd && pushd demuxlet
  - "autoreconf -vfi"
  - "./configure"
script: "make"
