language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - autoconf
    - automake
    - libtool
    - libbz2-dev
    - liblzma-dev
    - libcurl4-openssl-dev
    - libcrypto++-dev
    - zlib1g-devel

sudo: true

before_install:
  - ./install-protobuf.sh
install:
  - "autoreconf -vfi"
  - "./configure"
script: "make"
